"""Tool capability kernel: registry, execution pipeline, and schema DSL.

Ported from deepseek-harness packages/core/tools (MIT). ``ToolRuntime``
(``ctx.tools``) is the service; :mod:`pydsh.tools.json_schema` carries the
enforced JSON Schema subset, :mod:`pydsh.tools.schema` the author-facing DSL
and ``define_tool``, and :mod:`pydsh.tools.invariant` the pipeline
invariants. Code Mode, the SDK type renderers, the presentation vocabulary,
and the concrete tool implementations are out of scope for this port — see
:mod:`pydsh.tools.runtime` for the exact boundary.
"""

from .json_schema import (
    JsonSchemaError,
    JsonSchemaNode,
    JsonSchemaScalar,
    JsonSchemaType,
    ObjectJsonSchema,
    assert_object_json_schema,
    assert_supported_json_schema,
    is_json_schema_record,
    is_plain_json_array,
    validate_json_schema_value,
)
from .runtime import (
    RUN_CODE_NAME,
    TOOL_ABORTED,
    TOOL_ABORTED_BEFORE_DISPATCH,
    Config,
    DispatchFinalResult,
    DispatchPostResult,
    PostToolAccept,
    PostToolBlock,
    PostToolDecision,
    PreToolAllow,
    PreToolAsk,
    PreToolDecision,
    PreToolDeny,
    ScheduledDispatch,
    ScheduledFinalResult,
    ScheduledPostResult,
    ScheduledToolDispatch,
    ScheduledToolPreparation,
    ToolDefinition,
    ToolDispatchExecution,
    ToolErrorInfo,
    ToolExecution,
    ToolExecutionFailure,
    ToolExecutionInput,
    ToolExecutionMode,
    ToolExecutionResult,
    ToolExecutionSuccess,
    ToolExecutionToken,
    ToolFailure,
    ToolGuard,
    ToolNotFoundError,
    ToolOutputDefinition,
    ToolOutputError,
    ToolPresentationMode,
    ToolRestriction,
    ToolRunContext,
    ToolRuntime,
    ToolRuntimeScheduler,
)
from .schema import (
    ArrayValueSchemaSpec,
    BooleanValueSchemaSpec,
    DefineToolOutput,
    IntegerValueSchemaSpec,
    JsonValueSchemaSpec,
    NullValueSchemaSpec,
    NumberValueSchemaSpec,
    ObjectValueSchemaSpec,
    OneOfValueSchemaSpec,
    ParameterJsonSchema,
    ParameterPropertySpec,
    ParameterSchemaSpec,
    StringValueSchemaSpec,
    ToolArgsError,
    ValueSchemaAnnotations,
    ValueSchemaSpec,
    define_tool,
    parameter_schema_spec_to_json_schema,
    validate_args,
    value_schema_spec_to_json_schema,
)

__all__ = [
    'RUN_CODE_NAME',
    'TOOL_ABORTED',
    'TOOL_ABORTED_BEFORE_DISPATCH',
    'ArrayValueSchemaSpec',
    'BooleanValueSchemaSpec',
    'Config',
    'DefineToolOutput',
    'DispatchFinalResult',
    'DispatchPostResult',
    'IntegerValueSchemaSpec',
    'JsonSchemaError',
    'JsonSchemaNode',
    'JsonSchemaScalar',
    'JsonSchemaType',
    'JsonValueSchemaSpec',
    'NullValueSchemaSpec',
    'NumberValueSchemaSpec',
    'ObjectJsonSchema',
    'ObjectValueSchemaSpec',
    'OneOfValueSchemaSpec',
    'ParameterJsonSchema',
    'ParameterPropertySpec',
    'ParameterSchemaSpec',
    'PostToolAccept',
    'PostToolBlock',
    'PostToolDecision',
    'PreToolAllow',
    'PreToolAsk',
    'PreToolDecision',
    'PreToolDeny',
    'ScheduledDispatch',
    'ScheduledFinalResult',
    'ScheduledPostResult',
    'ScheduledToolDispatch',
    'ScheduledToolPreparation',
    'StringValueSchemaSpec',
    'ToolArgsError',
    'ToolDefinition',
    'ToolDispatchExecution',
    'ToolErrorInfo',
    'ToolExecution',
    'ToolExecutionFailure',
    'ToolExecutionInput',
    'ToolExecutionMode',
    'ToolExecutionResult',
    'ToolExecutionSuccess',
    'ToolExecutionToken',
    'ToolFailure',
    'ToolGuard',
    'ToolNotFoundError',
    'ToolOutputDefinition',
    'ToolOutputError',
    'ToolPresentationMode',
    'ToolRestriction',
    'ToolRunContext',
    'ToolRuntime',
    'ToolRuntimeScheduler',
    'ValueSchemaAnnotations',
    'ValueSchemaSpec',
    'assert_object_json_schema',
    'assert_supported_json_schema',
    'define_tool',
    'is_json_schema_record',
    'is_plain_json_array',
    'parameter_schema_spec_to_json_schema',
    'validate_args',
    'validate_json_schema_value',
    'value_schema_spec_to_json_schema',
]
