"""Event-sourced session capability: append-only log, store, derived history.

Ported from deepseek-harness packages/core/session (MIT). The in-memory
``SessionStore`` registers itself as the ``sessions`` service
(``ctx.sessions``); persistence is a plugin concern (subscribe to
``session/event``, drain on ``session/flush``).
"""

from .json import (
    SNAPSHOT_FAILED,
    JsonValue,
    SnapshotFailed,
    is_json_value,
    snapshot_json_value,
)
from .preparation import SessionPreparation
from .repair import (
    TOOL_NOT_STARTED,
    TOOL_OUTCOME_UNKNOWN,
    interrupted_turn_closers,
)
from .request_header import (
    call_config_equals,
    canonical_header,
    fold_request_header,
    header_equals,
)
from .store import (
    Session,
    SessionForkError,
    SessionForkErrorCode,
    SessionForkSource,
    SessionStore,
    adopt_session_event,
    snapshot_session_event,
)
from .surface import (
    SurfaceFoldReplacement,
    SurfaceFoldResult,
    SurfaceManager,
    derive_event_message,
    fold_surface,
    is_append_surface_event,
    is_replacement_surface_event,
    is_surface_eligible_type,
    is_surface_event,
)
from .types import (
    SESSION_FORMAT_VERSION,
    AgentCancelCause,
    AssistantChunkData,
    AssistantMessage,
    AssistantMessageData,
    CallId,
    ContentBlock,
    CreateSessionMeta,
    CreateSessionOptions,
    EpochHeader,
    LlmCallConfig,
    LlmCallConfigAdapterDefaults,
    LlmFailure,
    Message,
    MessageSource,
    PrepareSessionOptions,
    RequestContext,
    RequestHeaderData,
    RequestHeaderReason,
    RestoredSessionOptions,
    SessionEvent,
    SessionEventType,
    SessionHeader,
    SessionId,
    StepEndData,
    StepStartData,
    StreamChunk,
    SurfaceEventType,
    SurfaceIntent,
    SurfaceOp,
    SurfaceReplace,
    TodoItem,
    TodoWriteData,
    TokenUsage,
    ToolCallData,
    ToolResultData,
    ToolResultError,
    ToolResultMessage,
    ToolSchema,
    TurnEndData,
    TurnEndReason,
    TurnStartData,
    UserMessage,
)

__all__ = [
    'SESSION_FORMAT_VERSION',
    'SNAPSHOT_FAILED',
    'TOOL_NOT_STARTED',
    'TOOL_OUTCOME_UNKNOWN',
    'AgentCancelCause',
    'AssistantChunkData',
    'AssistantMessage',
    'AssistantMessageData',
    'CallId',
    'ContentBlock',
    'CreateSessionMeta',
    'CreateSessionOptions',
    'EpochHeader',
    'JsonValue',
    'LlmCallConfig',
    'LlmCallConfigAdapterDefaults',
    'LlmFailure',
    'Message',
    'MessageSource',
    'PrepareSessionOptions',
    'RequestContext',
    'RequestHeaderData',
    'RequestHeaderReason',
    'RestoredSessionOptions',
    'Session',
    'SessionEvent',
    'SessionEventType',
    'SessionForkError',
    'SessionForkErrorCode',
    'SessionForkSource',
    'SessionHeader',
    'SessionId',
    'SessionPreparation',
    'SessionStore',
    'SnapshotFailed',
    'StepEndData',
    'StepStartData',
    'StreamChunk',
    'SurfaceEventType',
    'SurfaceFoldReplacement',
    'SurfaceFoldResult',
    'SurfaceIntent',
    'SurfaceManager',
    'SurfaceOp',
    'SurfaceReplace',
    'TodoItem',
    'TodoWriteData',
    'TokenUsage',
    'ToolCallData',
    'ToolResultData',
    'ToolResultError',
    'ToolResultMessage',
    'ToolSchema',
    'TurnEndData',
    'TurnEndReason',
    'TurnStartData',
    'UserMessage',
    'adopt_session_event',
    'call_config_equals',
    'canonical_header',
    'derive_event_message',
    'fold_request_header',
    'fold_surface',
    'header_equals',
    'interrupted_turn_closers',
    'is_append_surface_event',
    'is_json_value',
    'is_replacement_surface_event',
    'is_surface_eligible_type',
    'is_surface_event',
    'snapshot_json_value',
    'snapshot_session_event',
]
